### ISSUE TITLE
Flush input, can't Log Data?

### ISSUE THREAD

**Issue by stopfortheklopp** [ShVerni/AirBeamLogger#3]
Hi, I've used this great tutorial for a few months now, but now I'm getting the following issue when trying to execute data_logger.py

Is it an issue with the sensor?
Also, when that error doesn't appear, I get the one that's shown before it.
Any help is greatly appreciated.

```
['']

traceback (most recent call last)

File "data_logger.py", line 40, in <module>

ser.flushInput()

```
https://imgur.com/a/rkAh8Q3

@ShVerni

**Comment by ShVerni** [comment]
Hi,

That's a new one to me, did you update Raspbian before this error started? It looks like it's having trouble talking to the Airbeam device. I'd make sure the Airbeam is fully charged and the USB cables is fully inserted into the Pi and try again (I've had trouble with cheap USB cables making a poor connection).

You can also test your AiBeam by plugging it into your computer and opening up a serial monitor like the Arduino one (which I recommend since Arduino also installs serial drivers on Windows) or PuTTY. Data with the current air readings should start appearing after a bit once the light on the AirBeam starts flashing. If it doesn't, then it could be a problem with the AirBeam itself.

If none of that works, I'll try to grab ours and see if I can reproduce your problem. Best of luck!

**Comment by stopfortheklopp** [comment]
Hi, 
Thank you so much for your quick reply.
Yes, I have updated Raspbian, and installed version 4.14 from scratch. I tried with several new Raspberry Pi B+ boards with different SD cards and even installed a previous raspbian image already configured with the Logger that worked for me perfectly a few months ago. I'll try using a new different sensor tomorrow, as it seems to be the issue now, and make sure that it's fully charged and test it with the Arduino serial monitor.

Again, thank you so much for this repository, it has truly helped me create consciousness in my community.

I'll update this post if any of this fixes the issue. 
Cheers

**Comment by ShVerni** [comment]
It's my pleasure, I'm so glad it can help. We've been using ours so Raspian hasn't been updated in a while, so there could be something new that's breaking things. I'll to update to the new Raspbian to see if that's the problem if none of the other fixes work.

**Comment by stopfortheklopp** [comment]
For anyone having this issue, the error stopped appearing once I created another Mobile session through the app, but for some reason it doesn't always work and the sensor sometimes stops streaming data when connected to the rasp. Hope this helps!

**Comment by ShVerni** [comment]
Thanks for the update, I'm glad you've found a work-around for the AirBeam at least. I'm going to include this a in a troubleshooting section of the repo so others can find it more easily. If you have have any other tips or issues, let me know.
